"""Testing migration error4.

Revision ID: 50df1097ea0e
Revises: 64d831b1e4b4
Create Date: 2022-10-20 10:35:08.155320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50df1097ea0e'
down_revision = '64d831b1e4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'legend_orientation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('legend_orientation', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
