"""Remove mplpdf and add fle type.

Revision ID: 67ceacde5cce
Revises: d27529cc6263
Create Date: 2022-10-07 23:28:38.978005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67ceacde5cce'
down_revision = 'd27529cc6263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('file_type', sa.String(length=3), nullable=True))
    op.drop_column('settings', 'mplpdf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('mplpdf', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('settings', 'file_type')
    # ### end Alembic commands ###
