"""Amending SimulationTask

Revision ID: 7ba42e51fb94
Revises: 5cb6c1b817bf
Create Date: 2023-03-19 21:28:50.635986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ba42e51fb94'
down_revision = '5cb6c1b817bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True))
        batch_op.drop_column('progress2')
        batch_op.drop_column('message2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message2', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress2', mysql.DOUBLE(asdecimal=True), nullable=True))
        batch_op.drop_column('done')

    # ### end Alembic commands ###
