"""Testing migration error3.

Revision ID: 8c1a0db82d7f
Revises: d28b9fcb7815
Create Date: 2022-10-20 10:19:43.565918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c1a0db82d7f'
down_revision = 'd28b9fcb7815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'legend_orientation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('legend_orientation', mysql.ENUM('horizontal', 'vertical'), nullable=True))
    # ### end Alembic commands ###
