"""Testing migration error.

Revision ID: 91b55719bfb7
Revises: 67ceacde5cce
Create Date: 2022-10-20 09:03:20.437343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b55719bfb7'
down_revision = '67ceacde5cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('foo', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'foo')
    # ### end Alembic commands ###
