"""Testing migration error4.

Revision ID: 9bf549ac28d9
Revises: 8c1a0db82d7f
Create Date: 2022-10-20 10:21:09.707318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf549ac28d9'
down_revision = '8c1a0db82d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('legend_orientation', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'legend_orientation')
    # ### end Alembic commands ###
