"""Changing done to is_done.

Revision ID: c60c38f00ac8
Revises: 7ba42e51fb94
Create Date: 2023-03-19 22:09:45.436079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c60c38f00ac8'
down_revision = '7ba42e51fb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), nullable=True))
        batch_op.drop_column('start_time_ms')
        batch_op.drop_column('done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_time_ms', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###
