"""fixing previous migration

Revision ID: cdb4ea32e0f3
Revises: d5149d86879a
Create Date: 2023-03-16 13:50:10.165313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdb4ea32e0f3'
down_revision = 'd5149d86879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.drop_constraint('simulation_task_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simulation_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'simulation_task', ['simulation_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('simulation_task_id')

    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('simulation_task_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
