"""graph lib -> plot type

Revision ID: d27529cc6263
Revises: eebefd5cc693
Create Date: 2022-10-07 22:55:41.868043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd27529cc6263'
down_revision = 'eebefd5cc693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('plot_type', sa.String(length=5), nullable=True))
    op.alter_column('settings', 'plot_orientation',
               existing_type=mysql.ENUM('horizontal', 'vertical'),
               nullable=True)
    op.drop_column('settings', 'graph_lib')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('graph_lib', mysql.VARCHAR(length=6), nullable=True))
    op.alter_column('settings', 'plot_orientation',
               existing_type=mysql.ENUM('horizontal', 'vertical'),
               nullable=False)
    op.drop_column('settings', 'plot_type')
    # ### end Alembic commands ###
