"""Adding start_time_ms to SimulationTask

Revision ID: f98c730d6527
Revises: cdb4ea32e0f3
Create Date: 2023-03-16 14:42:03.923062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98c730d6527'
down_revision = 'cdb4ea32e0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_task', schema=None) as batch_op:
        batch_op.drop_column('start_time_ms')

    # ### end Alembic commands ###
