"""Testing migration error6.

Revision ID: fc52d6fa7468
Revises: 50df1097ea0e
Create Date: 2022-10-20 10:35:34.299014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc52d6fa7468'
down_revision = '50df1097ea0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('legend_orientation', sa.Enum('h', 'v', name='legendorientation'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'legend_orientation')
    # ### end Alembic commands ###
