gvar = {
    'SCRIPTNAME_MAXLENGTH': 50,
    'CODE_MAXLENGTH': 10000,
    'EMAIL_MAXLENGTH': 50,  # Intentionally shorter than the wtforms.validators.Email() allows
    'PASSWORD_MAXLENGTH': 100,
    'USERNAME_MAXLENGTH': 100,

    'PLOTWIDTH_MINLENGTH': 10,
    'PLOTWIDTH_MAXLENGTH': 10000,
    'PLOTHEIGHT_MINLENGTH': 10,
    'PLOTHEIGHT_MAXLENGTH': 10000
}
